version: "3"
services:
  simple-todo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-todo
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules